name: deeptransfer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07
  - certifi=2018.8.13
  - cffi=1.11.5
  - cycler=0.10.0
  - freetype=2.9.1
  - icu=58.2
  - intel-openmp=2018.0.3
  - jpeg=9b
  - kiwisolver=1.0.1
  - libpng=1.6.34
  - matplotlib=2.2.3
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - numpy=1.15.0
  - numpy-base=1.15.0
  - openssl=1.0.2p
  - pip=10.0.1
  - pycparser=2.18
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - qt=5.9.6
  - setuptools=40.0.0
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.24.0
  - tornado=5.1
  - wheel=0.31.1
  - zlib=1.2.11
  - pillow
  - pyqt
  - pytorch=0.4.1
  - torchvision
